### ISSUE TITLE
test case finding inner hole

### ISSUE THREAD

**Issue by mischkew** [platener/jsclipper#5]
as discussed here https://github.com/platener/GreinerHormann/issues/11 jsclipper may be the right solution.

@romka-chev i implemented a small test case for your example. Works as expected. see here: https://github.com/platener/jsclipper/commit/d0e9b18992488f2861e7fe7155e37d9600eeacfd

Please let me know if you need more help.
A documentation for this library will not come up before next year.

**Comment by romka-chev** [comment]
Thank you - provided example looks great!

It's okay about docs - this one http://sourceforge.net/p/jsclipper/wiki/documentation/#overview sholud be enough.

Thank you again!

**Comment by mischkew** [comment]
Yeah alright. There shouldnt be too much code in the adapter file. We wanted to have a convenient access to the clipper lib. Currently we can do clip and offset operations. 
It should be too hard to extend or reuse the Polygon object for usage with extended jsclipper functionality. 

Thanks for your interest though. If you have trouble, please come back to us.
